line_length: warning
force_try: warning
type_body_length:
  - severity: warning
  - 350 # warning
disabled_rules: 
  - class_delegate_protocol
  - notification_center_detachment
  - identifier_name
  - empty_enum_arguments
  - multiple_closures_with_trailing_closure
  - todo
type_body_length:
  - 300 #warning
excluded: # paths to ignore during linting.
  - Pods
included:
  - ../GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help
  - ../GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Error
cyclomatic_complexity:
  ignores_case_statements: true
line_length:
    ignores_comments: true
    ignores_urls: true
file_length:
    ignore_comment_only_lines: true