sonar.projectKey=gini-mobile-ios-bank-sdk
sonar.organization=gini

# Project metadata
sonar.projectName=iOS Bank SDK
sonar.projectVersion=1.0

sonar.sources=GiniBankSDK
sonar.tests=GiniBankSDK/Tests
sonar.exclusions=**/Pods/**,**/*.xcassets/**,**/Resources/**,**/*.storyboard,**/*.xib,**/Tests/**
sonar.test.exclusions=**/Pods/**,**/*.xcassets/**

sonar.sourceEncoding=UTF-8

# Coverage
sonar.coverageReportPaths=coverage.xml
