# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

source 'https://github.com/gini/gini-podspecs.git'

target 'GiniBankSDKExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GiniBankSDKExample
  # Cannot use both at the same time. Commment/uncomment to only use one or the other.
  #pod 'GiniBankSDK'
  pod 'GiniBankSDKPinning'

end

target 'GiniBankSDKExampleBank' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GiniBankSDKExampleBank
  # Cannot use both at the same time. Commment/uncomment to only use one or the other.
  #pod 'GiniBankSDK'
  pod 'GiniBankSDKPinning'

end
