sonar.projectKey=gini_mobile_ios_health_sdk
sonar.organization=gini

# Project metadata
sonar.projectName=iOS Health SDK
sonar.projectVersion=1.0

sonar.sources=GiniHealthSDK/Sources
sonar.tests=GiniHealthSDK/Tests
sonar.exclusions=**/Pods/**,**/*.xcassets/**,**/Resources/**,**/*.storyboard,**/*.xib,**/Tests/**
sonar.test.exclusions=**/Pods/**,**/*.xcassets/**

sonar.sourceEncoding=UTF-8

# Coverage (if you generate coverage reports)
# sonar.coverageReportPaths=coverage.xml
