# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

load "util/lanes.rb"
load "util/versions.rb"
load "util/git.rb" 
load "util/swift_package_releases.rb"
load "util/add_files_to_project.rb"
load "util/sbom.rb"
import "Fastfile_signing"
import "Fastfile_archiving"

platform :ios do
  desc <<~DOC
    Publish a swift package to our release repository.
    
    Parameters:
      project_folder        - the folder of the project to be released (e.g., HealthAPILibrary, HealthSDK)"
      package_folder        - the folder to the swift package to be released (e.g., GiniHealthAPILibrary, GiniHealthAPILibraryPinning)"
      version_file_path     - the path to the file containing the package version
      git_tag               - the git tag name used to release the project
      repo_url              - the url of the release repository
      repo_user             - the username to use for authentication
      repo_password         - the password to use for authentication
      ci                    - set to "true" if running on a CI machine

  DOC
  lane :publish_swift_package do |options|
    (project_folder, package_folder, version_file_path, git_tag, repo_url, repo_user, repo_password, ci) = 
      check_and_get_options(options, [:project_folder, :package_folder, :version_file_path, :git_tag, :repo_url, :repo_user, :repo_password, :ci], UI)

      tag_version = get_project_version_from_tag(package_folder, git_tag, UI)
      package_version = get_project_version_from_version_file(version_file_path, UI)

      if tag_version != package_version
        UI.abort_with_message!  <<~MESSAGE
          Version in the tag is different from the package version:
            * tag       : #{tag_version}
            * project   : #{package_version}
          
          Change the version in the tag or update the packages's version in "#{version_file_path}".
        MESSAGE
      end

      UI.message <<~MESSAGE
        Will release to the release repository:
          * repository url  : #{repo_url}
          * project:        : #{project_folder}
          * swift package   : #{package_folder}
          * version         : #{package_version}
      MESSAGE

      if ci
        configure_git_on_ci_machines("Team Mobile Schorsch", "valentina.iancu@gini.net")
      end

      release_repo_path = checkout_release_repo(repo_url, repo_user, repo_password)

      copy_swift_package_to_release_repo(release_repo_path, project_folder, package_folder)

      update_release_repo(release_repo_path, package_version)
      
      UI.success <<~MESSAGE
        Successfully released to the release repository:
          * repository url  : #{repo_url}
          * project:        : #{project_folder}
          * swift package   : #{package_folder}
          * version         : #{package_version}
      MESSAGE

  end

  desc <<~DOC
  Build a documentation.
   
  Parameters:
    project_folder        - the folder of the project to be released (e.g., HealthAPILibrary, HealthSDK)
    package_folder        - the folder to the swift package to be released (e.g., GiniHealthAPILibrary, GiniHealthAPILibraryPinning)
  DOC
  lane :build_docs do |options|
    (project_folder, package_folder) = 
      check_and_get_options(options, [:project_folder, :package_folder], UI)
      
    jazzy config: "#{project_folder}/#{package_folder}/.jazzy.yaml"

    UI.success <<~MESSAGE
      Documentation successfully built:
        * available at    : #{project_folder}/#{package_folder}/Documentation/Api
    MESSAGE

  end

  desc <<~DOC
    Publish documentation to gh-pages.

    Releases the documentation into a folder hierarchy constructed from the package_folder and project version:
    <gh_pages_url>/<package_folder>/<project_version>
    Example: <gh_pages_url>/GiniCaptureSDK/1.11.0

    If the 'is_stable_release' option is set to true, then it updates the package root index.html 
    (at <gh_pages_url>/<package_folder>/index.html) to automatically redirect to the released version.
    
    Parameters:
      project_folder        - the folder of the project to be released (e.g., HealthAPILibrary, HealthSDK)
      package_folder        - the folder to the swift package to be released (e.g., GiniHealthAPILibrary, GiniHealthAPILibraryPinning)
      version_file_path     - the path to the file containing the package version
      git_tag               - the git tag name used to release the project
      ci                    - set to true if running on a CI machine
      documentation_title   - the title used on the root index page
      is_stable_release     - set to true if it's a stable release that should be shown by default 
      dry_run               - (optional) executes without permanent side effects

  DOC
  lane :publish_docs do |options|
    # Required options
    (project_folder, package_folder, version_file_path, git_tag, ci, documentation_title, is_stable_release) = 
      check_and_get_options(options, [:project_folder, :package_folder, :version_file_path, :git_tag, :ci, :documentation_title, :is_stable_release], UI)
      # Optional options
      dry_run = options[:dry_run]

      # Coerce boolean strings to actual booleans
      is_stable_release = is_stable_release.to_s.downcase == "true"
      ci = ci.to_s.downcase == "true"
      dry_run = dry_run.to_s.downcase == "true"

      # Validate GH_TOKEN is present
      if ENV['GH_TOKEN'].nil? || ENV['GH_TOKEN'].empty?
        UI.abort_with_message! "GH_TOKEN environment variable is required for publish_docs"
      end

      if ci
        configure_git_on_ci_machines("Team Mobile", "team-mobile@gini.net")
      end

      build_docs(project_folder: project_folder, package_folder: package_folder)

      tag_version = get_project_version_from_tag(package_folder, git_tag, UI)
      package_version = get_project_version_from_version_file(version_file_path, UI)

      if tag_version != package_version
        UI.abort_with_message!  <<~MESSAGE
          Version in the tag is different from the project version:
            * tag       : #{tag_version}
            * project   : #{package_version}
          
          Change the version in the tag or update the project's version in "#{version_file_path}"
        MESSAGE
      end

      UI.message <<~MESSAGE
      Start docs release:
        * project_folder      : #{project_folder}
        * package_folder      : #{package_folder}
        * package_version     : #{package_version}
        * git tag             : #{git_tag}
        * destination branch  : gh-pages
        * destination folder  : #{package_folder}/
        * url                 : "https://developer.gini.net/gini-mobile-ios/#{package_folder}/index.html"
     MESSAGE

      # Clear gh-pages directory 
      sh("rm -rf gh-pages")

      # Create a temporary credential helper script that uses GH_TOKEN
      # This approach keeps the token out of command lines and process listings
      credential_helper = "/tmp/git-credential-helper-#{Process.pid}.sh"
      
      begin
        File.write(credential_helper, <<~SCRIPT)
          #!/bin/bash
          echo "username=x-access-token"
          echo "password=${GH_TOKEN}"
        SCRIPT
        sh("chmod +x #{credential_helper}")
        
        # Configure git to use the credential helper and clone
        sh("git config --global credential.helper '#{credential_helper}'")
        sh("git clone -b gh-pages https://github.com/gini/gini-mobile-ios.git gh-pages")

        destination_path = "#{package_folder}/#{package_version}"

        Dir.chdir("gh-pages") do
          UI.message "Clear out the existing documentation"
          sh("git rm -rf #{destination_path} --ignore-unmatch && git clean -fd")

          UI.message "Copy over the current documentation"
          sh("mkdir -p #{destination_path} && cp -R ../../#{project_folder}/#{package_folder}/Documentation/Api/ #{destination_path}")

          UI.message "Disable jekyll"
          sh("touch .nojekyll")

          if is_stable_release
            UI.message <<~MESSAGE
              Update the package root index.html to redirect to this documentation version.
            MESSAGE
      
            index_html = <<~INDEX_HTML
            <!DOCTYPE html>
            <html lang="en">
              <head>
                <meta charset="UTF-8">
                <title>#{documentation_title}</title>
                <meta http-equiv="refresh" content="0; URL=https://developer.gini.net/gini-mobile-ios/#{destination_path}/index.html" />
              </head>
              <body>
                Redirecting to the latest stable version...
              </body>
            </html>
            INDEX_HTML
      
            File.open("#{package_folder}/index.html", "w") { |f| 
              f.write index_html
            }
          else
            UI.message "Skipping root index.html update (not a stable release)"
          end

          if !dry_run 
            UI.message "Commit and push the new documentation"
            sh("git add --all")
            sh("git diff --quiet --exit-code --cached || git commit -m 'Release #{package_folder} documentation for tag #{git_tag}' --author='Team Mobile <team-mobile@gini.net>'")
            git_push_with_retry("gh-pages", UI)
          else
            UI.message "Skipping commit and push (dry run)"
          end
        end
      ensure
        # Clean up credential helper and git config
        sh("git config --global --unset credential.helper || true")
        sh("rm -f #{credential_helper}")
      end

      UI.success <<~MESSAGE
      Documentation released:
        * project_folder      : #{project_folder}
        * package_folder      : #{package_folder}
        * git_tag             : #{git_tag}
        * destination branch  : gh-pages
        * destination folder  : #{package_folder}/
        * url                 : https://developer.gini.net/gini-mobile-ios/#{package_folder}/index.html
      MESSAGE
  end

  desc <<~DOC
    Create release tags for all packages that have different versions than their latest release tag.
  DOC
  lane :create_release_tags do |options|

    # Not all packages require own release tags (some are released automatically with other packages)
    ignored_packages = [/\/.+Pinning\//]

    Dir.chdir("..") do
      # Gather all packages which have a (...)Version.swift file
      packages = Dir["./**/*Version.swift"]
        .map { |version_file|
          if ignored_packages.find { |ignored| version_file =~ ignored }
            next nil
          end

          contents = File.open(version_file).read

          if match = contents.match(/=.*?"(.+)"/)
            components = version_file.split("/")
            { :package_folder => components[2], :version => match.captures[0] }
          end
        }
        .compact

      up_to_date = []
      to_be_released = []

      # Create release tags for packages which have different versions than their latest release tag
      # Create release tags for packages which have different versions than their latest release tag
      packages.each do |package|
        latest_version = get_latest_version_from_release_tags(package[:package_folder], UI)

        if latest_version.nil?
          UI.message("No release tags found for #{package[:package_folder]}, treating as a new package.")
          # Treat the package as new and create a release tag
          to_be_released.push package
          git_create_release_tag(package[:package_folder], package[:version])

          if UI.confirm("Push release tag?")
            git_push_release_tag(package[:package_folder], package[:version])
          end
        elsif package[:version] == latest_version
          # The current package version is the same as the one in the latest release tag
          UI.message("#{package[:package_folder]} is up to date with version #{package[:version]}.")
          up_to_date.push package
        elsif git_has_release_tag(package[:package_folder], package[:version])
          # The current package version has already been released
          UI.message("#{package[:package_folder]} version #{package[:version]} has already been released.")
          up_to_date.push package
        else
          # The package version needs a new release tag
          UI.message("#{package[:package_folder]} version #{package[:version]} will be tagged as a new release.")
          to_be_released.push package
          git_create_release_tag(package[:package_folder], package[:version])

        if UI.confirm("Push release tag?")
          git_push_release_tag(package[:package_folder], package[:version])
         end
        end
      end


      if to_be_released.empty?
        UI.success "All packages are up-to-date. No release tags needed."
      else
        UI.message <<~MESSAGE
            Following packages are up-to-date:
              #{up_to_date.map{ |package| "- #{package[:package_folder]} #{package[:version]}" }.join("\n  ") }
          MESSAGE

        UI.success <<~MESSAGE
            Created release tags for:
              #{to_be_released.map{ |package| "- #{package[:package_folder]} #{package[:version]}" }.join("\n  ") }
          MESSAGE
      end
    end
  end
  
  desc <<~DOC
    Create documentation release tags for all packages that have documentation that changed since their latest release.
  DOC
  lane :create_documentation_release_tags do
    Dir.chdir("..") do
      new_doc_release_tags = Dir["./**/Documentation"]
        .filter { |doc_dir|
          # Gather all projects which have documentation that changed since the last release
          components = doc_dir.split("/")
          puts components
          package_folder = components[2]
          puts package_folder
          did_folder_change_since_last_release(package_folder, doc_dir, UI)
        }
        .map { |doc_dir|
          # Create documentation release tags
          components = doc_dir.split("/")
          package_folder = components[2]
          latest_release_tag = get_latest_release_tag(package_folder)

          if match = latest_release_tag.match(/(^.*?;)doc.*?([0-9]+)/)
            next_doc_release_nr = match.captures[1].to_i + 1
            "#{match.captures[0]}doc-#{next_doc_release_nr}"
          else
            "#{latest_release_tag};doc-1"
          end
        }

      puts new_doc_release_tags
      
      if new_doc_release_tags.empty?
        UI.success "Every documentation is up-to-date. No documentation release tags needed."
      else
        # Create and push tags
        new_doc_release_tags.each do |new_doc_release_tag|
          git_create_tag(new_doc_release_tag)

          if UI.confirm("Push documentation release tag?")
            git_push_tag(new_doc_release_tag)
          end
        end
        
        UI.success <<~MESSAGE
            Created documentation release tags for:
              #{new_doc_release_tags.map{ |tag| "- #{tag}" }.join("\n  ") }
          MESSAGE
      end
    end
  end

  desc <<~DOC
    Setup Manual Signing for project at path
  DOC
  lane :setup_manual_signing do |options|
    (project_path, team_id, target, bundle_identifier, profile_name, entitlements_file_path, ci) = 
      check_and_get_options(options, [:project_path, :team_id, :target, :bundle_identifier, :profile_name, :entitlements_file_path, :ci], UI)
    # Optional options
    target_extension = options[:target_extension]
    bundle_identifier_extension = options[:bundle_identifier_extension]
    profile_name_extension = options[:profile_name_extension]
    entitlements_file_path_extension = options[:entitlements_file_path_extension]

    update_code_signing_settings(
      use_automatic_signing: false,
      path: project_path,
      team_id: team_id,
      targets: target,
      bundle_identifier: bundle_identifier,
      profile_name: profile_name,
      entitlements_file_path: entitlements_file_path
    )
    # For signing an extension you need to pass the following params: target_extension, bundle_identifier_extension, profile_name_extension, entitlements_file_path_extension
    if (target_extension && bundle_identifier_extension && profile_name_extension && entitlements_file_path_extension)
    update_code_signing_settings(
      use_automatic_signing: false,
      path: project_path,
      team_id: team_id,
      targets: target_extension,
      bundle_identifier: bundle_identifier_extension,
      profile_name: profile_name_extension,
      entitlements_file_path: entitlements_file_path_extension
    )
    end
  end
  
  desc <<~DOC
    Add Resources to Project file
  DOC
  lane :add_resources do |options|
    (project_path, resource_name, target_name, resources_path, ci) = 
      check_and_get_options(options, [:project_path, :resource_name, :target_name, :resources_path, :ci], UI)

    project = Xcodeproj::Project.open(project_path)
    targetSDK = project.targets.find { |target| target.to_s == target_name }
    resourcesgroup = project.new_group(resource_name)
    addFiles("#{resources_path}/*", resourcesgroup, targetSDK)
    project.save
  end

  desc <<~DOC
    Generate CycloneDX SBOMS for all swift packages. The SBOMs are zipped and uploaded to GitHub.
    
    Parameters:
      swift_package_repo_urls     - the list of swift package repository urls
      repo_user                   - the username to use for authentication
      repo_password               - the password to use for authentication
      ci                          - set to "true" if running on a CI machine

  DOC
  lane :generate_sboms do |options|
    (swift_package_repo_urls, repo_user, repo_password, ci) = 
      check_and_get_options(options, [:swift_package_repo_urls, :repo_user, :repo_password, :ci], UI)

      UI.message <<~MESSAGE
        Will generate CycloneDX SBOMs for swift packages:
          * swift package repository urls  : #{swift_package_repo_urls}
      MESSAGE

      if ci
        configure_git_on_ci_machines("Team Mobile Schorsch", "valentina.iancu@gini.net")
      end

      sbom_paths = []

      swift_package_repos = swift_package_repo_urls.split(",").map(&:strip)

      swift_package_repos.each do |repo_url|
        release_repo_path = clone_repo(repo_url, repo_user, repo_password, 1)
        sbom_path = generate_sbom(release_repo_path)

        sbom_paths.push sbom_path
      end

      all_sboms_zip_file_name = "sbom-jsons.zip"
      
      sh("zip -rj #{all_sboms_zip_file_name} #{sbom_paths.join(" ")}")
      
      UI.success <<~MESSAGE
        Successfully generated CycloneDX SBOMS for all swift packages:
          * swift package repository urls   : #{swift_package_repo_urls}
          * generated sbom paths                 : #{sbom_paths.map{ |path| "fastlane/#{path}" }.join(", ")}
          * location of zip with all sboms  : "fastlane/#{all_sboms_zip_file_name}"
      MESSAGE

  end

  desc <<~DOC
  Generate a release podspec and publish it on https://github.com/gini/gini-podspecs.
  
  Parameters:
    xcframeworks_folder_path        - path to the folder which contains the .xcframeworks files
    pod_name                        - name of the pod, usually the same as the Swift package name, e.g. GiniBankSDK or GiniCaptureSDKPinning
    podspecs_repo_sdk_folder_path   - path to the folder which contains the local clone of the https://github.com/gini/gini-podspecs repo
    template_podspec_path           - path to the template podspec file, which is modified and used for the new pod version e.g: BankSDK/GiniBankSDK/Pod/GiniBankSDK.podspec

  DOC
  lane :publish_podspec do |options|

    (xcframeworks_folder_path, pod_name, podspecs_repo_sdk_folder_path, template_podspec_path) = 
      check_and_get_options(options, [:xcframeworks_folder_path, :pod_name, :podspecs_repo_sdk_folder_path, :template_podspec_path], UI)
    
    # Extract the version from the tag (assuming the tag format is "GiniBankSDK;X.X.X")
    # Remove "Pinning" suffix, if needed, because we don't tag pinning releases separately (pinning version is released together with the non-pinning version)
    project_id = pod_name.sub('Pinning', '') 
    version_folder = get_latest_version_from_release_tags(project_id, UI)
    
    # Step 1: Compress the XCFrameworks into a zip file
    zip_name = "#{pod_name}-XCFrameworks.zip" #e.g GiniBankSDK or GiniBankSDKPinning
    sh "cd #{xcframeworks_folder_path} && zip -r #{zip_name} ."
    
    # Step 2: Create a subfolder named after the version
    sdk_folder = "#{xcframeworks_folder_path}/#{version_folder}"
    sh "mkdir -p #{sdk_folder}"

    # Step 3: Copy the zip file and podspec into the new folder
    sh "cp #{xcframeworks_folder_path}/#{zip_name} #{sdk_folder}/"
    # template_podspec_path sould look like: BankSDK/GiniBankSDK/Pod/GiniBankSDK.podspec or BankSDK/GiniBankSDKPinning/Pod/GiniBankSDKPinning.podspec
    sh "cp #{template_podspec_path} #{sdk_folder}/"
    
    # Step 4: Update the version in the podspec
    podspec_file_path = "#{sdk_folder}/#{pod_name}.podspec"
    sh "sed -i '' 's/spec.version[[:space:]]*=[[:space:]]*\".*\"/spec.version = \"#{version_folder}\"/' #{podspec_file_path}"

    # Step 5: Copy the recently created version folder (e.g. 3.7.2) in gini-podspecs repo folder
    sh "cp -r #{sdk_folder} #{podspecs_repo_sdk_folder_path}/"

    # Step 6: Commit the changes to gini-podspecs repo
    sh "cd #{podspecs_repo_sdk_folder_path} && git add . && git commit -m '[Update] #{pod_name} (#{version_folder})'" 

    # Step 7: Push the changes to gini-podspecs repo
    if UI.confirm("Are you sure you want to push these changes to the https://github.com/gini/gini-podspecs repo?")
      sh "cd #{podspecs_repo_sdk_folder_path} && git push origin master"
    end
  end

desc <<~DOC
Runs unit tests for a given target using the `scan` action (a wrapper around xcodebuild).

Parameters:
- `target`: The name of the target whose test scheme will be executed. Example: `GinBankSDK`.
- `destination`: The destination for the tests. Example: `platform=iOS Simulator,name=iPhone 15,OS=17.4`.
- `clientId`: (Optional) The clientId for the hosting app. If provided, clientSecret must also be provided.
- `clientSecret`: (Optional) The clientSecret for the hosting app. If provided, clientId must also be provided.
DOC

lane :run_unit_tests do |options|
  target = options[:target]
  destination = options[:destination]
  clientId = options[:clientId]
  clientSecret = options[:clientSecret]
  result_bundle_path = options[:result_bundle_path]

  unless target && destination
    UI.user_error!("Missing 'target' or 'destination' parameter. Pass both to run the tests.")
  end

  # Validate that clientId and clientSecret are used together
  if (clientId && !clientSecret) || (!clientId && clientSecret)
    UI.user_error!("clientId and clientSecret must be provided together or not at all.")
  end

  # Build xcargs array conditionally
  xcargs = [
    'CODE_SIGNING_REQUIRED=NO',
    'CODE_SIGN_IDENTITY=""',
    'ONLY_ACTIVE_ARCH=NO'
  ]
  
  # Add CLIENT_ID and CLIENT_SECRET only if both are provided
  if clientId && clientSecret && !clientId.empty? && !clientSecret.empty?
    xcargs << "CLIENT_ID=#{clientId}"
    xcargs << "CLIENT_SECRET=#{clientSecret}"
  end

  scan(
    workspace: "GiniMobile.xcworkspace",
    scheme: target,
    clean: true,
    destination: destination,
    disable_concurrent_testing: false,
    xcargs: xcargs.join(' '),
    output_types: "",                 # prevent report generation
    output_directory: "./tmp_test_output",
    fail_build: true,
    code_coverage: true,
    result_bundle: !result_bundle_path.nil?,
    result_bundle_path: result_bundle_path
  )
  
  # Clean up the report files that were generated
  sh("rm -rf ./tmp_test_output") if File.exist?("./tmp_test_output")
end

desc <<~DOC
  Builds targets using the `gym` action (a wrapper around xcodebuild).

  This lane builds the specified target without code signing or archiving, useful for
  CI/CD pipelines where you only need to verify the build succeeds.

  Parameters:
  - `scheme`: The name of the scheme to build. Example: `GiniBankSDK`.
  - `destination`: The destination for the build. Example: `platform=iOS Simulator,name=iPhone 15,OS=17.4`.
DOC
lane :build_scheme do |options|
  gym(
    workspace: "GiniMobile.xcworkspace",
    scheme: options[:target],
    destination: options[:destination],
    skip_codesigning: true,
    skip_archive: true,
    skip_package_ipa: true,
    xcargs: {
      "CODE_SIGN_IDENTITY" => "",
      "CODE_SIGNING_REQUIRED" => "NO",
      "ONLY_ACTIVE_ARCH" => "NO"
    }
  )
end
desc <<~DOC
  Register new devices from a devices file.
  
  This lane reads device UDIDs, names, and platforms from a text file and registers them
  with your Apple Developer account. The devices file should contain one device
  per line in the format from the content of the `./devices.txt` file.
  
  Parameters:
    devices_file - Path to the devices file (default: "./devices.txt")
  
  Example devices.txt format:
    1234567890abcdef1234567890abcdef12345678	John's ios
    abcdef1234567890abcdef1234567890123456	Jane's ios
DOC
lane :register_new_devices do 
    register_devices(devices_file: "./devices.txt")
end


  desc <<~DOC
    Generic lane: archive and export any iOS app as an .ipa for App Store / TestFlight distribution.

    Uses manual signing — provisioning profiles must already be installed on the machine
    (or set up by setup_manual_signing in CI).

    Parameters:
      project            - Path to the .xcodeproj (relative to repo root)
      scheme             - Xcode scheme to build
      output_name        - IPA filename without extension (default: scheme name)
      output_directory   - Directory to write the IPA into (default: ".")
      team_id            - Apple Developer Team ID (default: "JA825X8F7Z")
      provisioning_profiles - Hash of { bundle_id => profile_name } (required)
      configuration      - Build configuration (default: "Release")
  DOC
  lane :archive_ios_app do |options|
    project     = options[:project]     || UI.user_error!("Missing required option: project")
    scheme      = options[:scheme]      || UI.user_error!("Missing required option: scheme")
    profiles    = options[:provisioning_profiles] || UI.user_error!("Missing required option: provisioning_profiles")
    # When called from the CLI, options arrive as strings — parse JSON if needed
    profiles    = JSON.parse(profiles) if profiles.is_a?(String)
    output_name = options[:output_name]      || scheme
    output_dir  = options[:output_directory] || "."
    team_id     = options[:team_id]          || "JA825X8F7Z"
    config      = options[:configuration]    || "Release"

    gym(
      project: project,
      scheme: scheme,
      configuration: config,
      clean: true,
      export_method: "app-store",
      export_options: {
        provisioningProfiles: profiles,
        signingStyle: "manual",
        signingCertificate: "Apple Distribution",
        teamID: team_id,
        stripSwiftSymbols: true,
        thinning: "<none>"
      },
      destination: "generic/platform=iOS",
      output_directory: output_dir,
      output_name: output_name
    )
  end

  desc <<~DOC
    Build any iOS app IPA and upload it to TestFlight in one step.

    Parameters:
      project               - Path to the .xcodeproj (relative to repo root)
      scheme                - Xcode scheme to build
      ipa_name              - IPA filename without extension (default: scheme name)
      output_directory      - Directory to write the IPA into (default: ".")
      team_id               - Apple Developer Team ID (default: "JA825X8F7Z")
      provisioning_profiles - Hash of { bundle_id => profile_name } (required)
      configuration         - Build configuration (default: "Release")

    Environment Variables:
      APP_STORE_CONNECT_API_KEY_ID      - App Store Connect API key ID
      APP_STORE_CONNECT_API_ISSUER_ID   - App Store Connect API issuer ID
      APP_STORE_CONNECT_API_KEY_PATH    - Path to the .p8 API key file
  DOC
  lane :build_and_upload_to_testflight do |options|
    ipa_name       = options[:ipa_name] || options[:scheme] || UI.user_error!("Missing required option: ipa_name or scheme")
    output_dir     = options[:output_directory] || "."

    archive_ios_app(options.merge(output_name: ipa_name, output_directory: output_dir))
    publish_to_testflight(ipa_path: "#{output_dir}/#{ipa_name}.ipa")
  end

  desc <<~DOC
    Upload an .ipa to TestFlight via xcrun altool.

    Parameters:
      ipa_path - Path to the .ipa file (default: "./GiniBankSDKExample.ipa")

    Environment Variables:
      APP_STORE_CONNECT_API_KEY_ID      - App Store Connect API key ID
      APP_STORE_CONNECT_API_ISSUER_ID   - App Store Connect API issuer ID
      APP_STORE_CONNECT_API_KEY_PATH    - Path to the .p8 API key file
                                          (default: build_artifacts/AppStoreConnectAPIKey.p8)
  DOC
  lane :publish_to_testflight do |options|
    ipa_path  = options[:ipa_path] || "./GiniBankSDKExample.ipa"
    key_id    = ENV['APP_STORE_CONNECT_API_KEY_ID']
    issuer_id = ENV['APP_STORE_CONNECT_API_ISSUER_ID']
    key_path  = ENV['APP_STORE_CONNECT_API_KEY_PATH'] || "build_artifacts/AppStoreConnectAPIKey.p8"

    repo_root         = File.expand_path("..", __dir__)
    resolved_key_path = File.expand_path(key_path, repo_root)
    resolved_ipa_path = File.expand_path(ipa_path, repo_root)

    UI.user_error!("APP_STORE_CONNECT_API_KEY_ID is not set")    if key_id.nil? || key_id.empty?
    UI.user_error!("APP_STORE_CONNECT_API_ISSUER_ID is not set") if issuer_id.nil? || issuer_id.empty?
    UI.user_error!("API key not found at: #{resolved_key_path}") unless File.exist?(resolved_key_path)
    UI.user_error!("IPA not found at: #{resolved_ipa_path}")     unless File.exist?(resolved_ipa_path)

    # xcrun altool reads .p8 keys from ~/.appstoreconnect/private_keys/AuthKey_<ID>.p8
    private_keys_dir      = File.expand_path("~/.appstoreconnect/private_keys")
    expected_key_path     = "#{private_keys_dir}/AuthKey_#{key_id}.p8"
    created_temporary_key = false
    sh("mkdir -p '#{private_keys_dir}'")
    unless resolved_key_path == expected_key_path
      sh("cp '#{resolved_key_path}' '#{expected_key_path}'")
      created_temporary_key = true
    end
    # Ensure restrictive permissions on the API key file
    sh("chmod 600 '#{expected_key_path}'") if File.exist?(expected_key_path)

    begin
      UI.message "🚀 Uploading #{resolved_ipa_path} to TestFlight..."
      sh(
        "xcrun altool --upload-app" \
        " --file '#{resolved_ipa_path}'" \
        " --type ios" \
        " --apiKey '#{key_id}'" \
        " --apiIssuer '#{issuer_id}'"
      )
    ensure
      # Remove the temporary key copy to avoid leaving credentials on disk
      sh("rm -f '#{expected_key_path}'") if created_temporary_key
    end
  end

end
