sonar.projectKey=gini-mobile-ios-capture-sdk
sonar.projectName=iOS Capture SDK
sonar.projectVersion=1.0

sonar.sources=GiniCaptureSDK
sonar.tests=GiniCaptureSDK/Tests
sonar.exclusions=**/Pods/**,**/*.xcassets/**,**/Resources/**,**/*.storyboard,**/*.xib,**/Tests/**
sonar.test.exclusions=**/Pods/**,**/*.xcassets/**

sonar.sourceEncoding=UTF-8
sonar.language=swift

# Coverage (if you generate coverage reports)
# sonar.coverageReportPaths=coverage.xml
