sonar.projectKey=gini-mobile-ios-capture-sdk
sonar.projectName=iOS Capture SDK

sonar.sources=GiniCaptureSDK
sonar.tests=GiniCaptureSDK/Tests
sonar.exclusions=**/Pods/**,**/*.xcassets/**,**/Resources/**,**/*.storyboard,**/*.xib,**/Tests/**
sonar.test.exclusions=**/Pods/**,**/*.xcassets/**

sonar.sourceEncoding=UTF-8

# Coverage (if you generate coverage reports)
sonar.coverageReportPaths=coverage.xml
