name: Builds docs for Bank SDK

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - 'BankSDK/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'refs/tags/')}}
  
jobs:
  documentation:
    runs-on: macos-latest
    permissions:
      contents: read
    steps:
    - uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
      with:
        xcode-version: '15.3'

    - name: Checkout
      uses: actions/checkout@v4

    - name: setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.0'
        bundler-cache: true

    - name: Build GiniBankSDK documentation
      uses: maierj/fastlane-action@v3.1.0
      with:
        lane: 'build_docs'
        options: >
          { 
            "project_folder": "BankSDK",
            "package_folder": "GiniBankSDK"
          }

    - name: archive documentation
      uses: actions/upload-artifact@v4
      with:
        name: GiniBankSDKDocumentation
        path: BankSDK/GiniBankSDK/Documentation/Api        
