name: Release Bank SDK
on:
  push:
    tags:
      - 'GiniBankSDK;[0-9]+.[0-9]+.[0-9]+'
      - 'GiniBankSDK;[0-9]+.[0-9]+.[0-9]+-beta[0-9][0-9]'
  workflow_dispatch:
 
jobs:
  check:
    uses: gini/gini-mobile-ios/.github/workflows/bank-sdk.check.yml@main
    secrets:
      GINI_MOBILE_TEST_CLIENT_SECRET: ${{ secrets.GINI_MOBILE_TEST_CLIENT_SECRET }}
  
  release:
    needs: check
    runs-on: macos-latest   
    steps:
    - uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: '15.3'

    - name: Checkout
      uses: actions/checkout@v4

    - name: setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.0'
        bundler-cache: true

    - name: Publish GiniBankSDK package to the release repo
      uses: maierj/fastlane-action@v3.1.0
      with:
        lane: 'publish_swift_package'
        options: >
          { 
            "project_folder": "BankSDK",
            "package_folder": "GiniBankSDK",
            "version_file_path": "BankSDK/GiniBankSDK/Sources/GiniBankSDK/GiniBankSDKVersion.swift",
            "git_tag": "${{ github.ref }}", 
            "repo_url": "https://github.com/gini/bank-sdk-ios.git", 
            "repo_user": "${{ secrets.RELEASE_GITHUB_USER }}",
            "repo_password": "${{ secrets.RELEASE_GITHUB_PASSWORD }}",
            "ci": "true"
          }

    - name: Publish GiniBankSDKPinning package to the release repo
      uses: maierj/fastlane-action@v3.1.0
      with:
        lane: 'publish_swift_package'
        options: >
          { 
            "project_folder": "BankSDK",
            "package_folder": "GiniBankSDKPinning",
            "version_file_path": "BankSDK/GiniBankSDKPinning/Sources/GiniBankSDKPinning/GiniBankSDKPinningVersion.swift",
            "git_tag": "${{ github.ref }}", 
            "repo_url": "https://github.com/gini/bank-sdk-pinning-ios.git", 
            "repo_user": "${{ secrets.RELEASE_GITHUB_USER }}",
            "repo_password": "${{ secrets.RELEASE_GITHUB_PASSWORD }}",
            "ci": "true"
          }      

  release-documentation:
    needs: release
    uses: gini/gini-mobile-ios/.github/workflows/bank-sdk.publish.docs.yml@main
    secrets:
      RELEASE_GITHUB_USER: ${{ secrets.RELEASE_GITHUB_USER }}
      RELEASE_GITHUB_PASSWORD: ${{ secrets.RELEASE_GITHUB_PASSWORD }}

  build-xcframeworks:
    needs: release
    uses: gini/gini-mobile-ios/.github/workflows/bank-sdk.build.xcframeworks.yml@main
    secrets:
      BUILD_CERTIFICATE_BASE64: ${{ secrets.GINI_DISTRIBUTION_CERTIFICATE }}
      P12_PASSWORD: ${{ secrets.GINI_DISTRIBUTION_CERTIFICATE_SECRET }}
      BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.GINI_BANK_SDK_EXAMPLE_ADHOC_DISTRIBUTION_PROVISION_PROFILE }}
      BUILD_PROVISION_PROFILE_EXTENSION_BASE64: ${{ secrets.GINI_BANK_SDK_EXTENSION_ADHOC_DISTRIBUTION_PROVISION_PROFILE }}
      KEYCHAIN_PASSWORD: ${{ secrets.GINI_DISTRIBUTION_CERTIFICATE_SECRET }}