name: Release Bank API Library
permissions:
  contents: write
on:
  push:
    tags:
      - 'GiniBankAPILibrary;[0-9]+.[0-9]+.[0-9]+'
      - 'GiniBankAPILibrary;[0-9]+.[0-9]+.[0-9]+-beta[0-9][0-9]'
  workflow_dispatch:

jobs:
  get-config:
    uses: ./.github/workflows/shared-config.yml

  check:
    needs: get-config
    uses: gini/gini-mobile-ios/.github/workflows/bank-api-library.check.yml@main
    secrets:
      GINI_MOBILE_TEST_CLIENT_SECRET: ${{ secrets.GINI_MOBILE_CI_PASSWORD }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  release:
    needs: [get-config, check]
    permissions:
      contents: write
    uses: ./.github/workflows/sdk.release.yml
    with:
      project_folder: 'BankAPILibrary'
      package_folder: 'GiniBankAPILibrary'
      version_file_path: 'BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/GiniBankAPILibraryVersion.swift'
      git_tag: ${{ github.ref }}
      repo_url: 'https://github.com/gini/bank-api-library-ios.git'
      xcode-version: ${{ needs.get-config.outputs.xcode-version }}
      ruby-version: ${{ needs.get-config.outputs.ruby-version }}
    secrets:
      MOBILE_CI_APP_ID: ${{ secrets.MOBILE_CI_APP_ID }}
      MOBILE_CI_APP_PRIVATE_KEY: ${{ secrets.MOBILE_CI_APP_PRIVATE_KEY }}

  release-documentation:
    needs: release
    uses: gini/gini-mobile-ios/.github/workflows/bank-api-library.publish.docs.yml@main
    secrets:
      MOBILE_CI_APP_ID: ${{ secrets.MOBILE_CI_APP_ID }}
      MOBILE_CI_APP_PRIVATE_KEY: ${{ secrets.MOBILE_CI_APP_PRIVATE_KEY }}
