name: Release Bank SDK
permissions:
  contents: write
on:
  push:
    tags:
      - 'GiniBankSDK;[0-9]+.[0-9]+.[0-9]+'
      - 'GiniBankSDK;[0-9]+.[0-9]+.[0-9]+-beta[0-9][0-9]'
  workflow_dispatch:
 
jobs:
  check:
    uses: gini/gini-mobile-ios/.github/workflows/bank-sdk.check.yml@main
    secrets:
      GINI_MOBILE_CI_PASSWORD: ${{ secrets.GINI_MOBILE_CI_PASSWORD }}
      GINI_MOBILE_CI_USERNAME: ${{ secrets.GINI_MOBILE_CI_USERNAME }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
  release:
    needs: check
    permissions:
      contents: write
    uses: ./.github/workflows/sdk.release.yml
    with:
      project_folder: 'BankSDK'
      package_folder: 'GiniBankSDK'
      version_file_path: 'BankSDK/GiniBankSDK/Sources/GiniBankSDK/GiniBankSDKVersion.swift'
      git_tag: ${{ github.ref }}
      repo_url: 'https://github.com/gini/bank-sdk-ios.git'
    secrets:
      MOBILE_CI_APP_ID: ${{ secrets.MOBILE_CI_APP_ID }}
      MOBILE_CI_APP_PRIVATE_KEY: ${{ secrets.MOBILE_CI_APP_PRIVATE_KEY }}

  release-documentation:
    needs: release
    uses: gini/gini-mobile-ios/.github/workflows/bank-sdk.publish.docs.yml@main
    secrets:
      MOBILE_CI_APP_ID: ${{ secrets.MOBILE_CI_APP_ID }}
      MOBILE_CI_APP_PRIVATE_KEY: ${{ secrets.MOBILE_CI_APP_PRIVATE_KEY }}

  # build-xcframeworks:
  #   needs: release
  #   uses: gini/gini-mobile-ios/.github/workflows/bank-sdk.build.xcframeworks.yml@main
  #   secrets:
  #     KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
