name: Release Bank SDK
on:
  push:
    tags:
      - 'GiniBankSDK;[0-9]+.[0-9]+.[0-9]+'
  
jobs:
  check:
    uses: gini/gini-mobile-ios/.github/workflows/bank-sdk.check.yml@main

  release:
    needs: check
    runs-on: macOS-11    
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.0'

    - name: Checkout
      uses: actions/checkout@v2

    - name: setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true

    - name: Publish GiniBankSDK package to the release repo
      uses: maierj/fastlane-action@v2.0.1
      with:
        lane: 'publish_swift_package'
        options: >
          { 
            "project_folder": "BankSDK",
            "package_folder": "GiniBankSDK",
            "version_file_path": "BankSDK/GiniBankSDK/Sources/GiniBankSDK/GiniBankSDKVersion.swift",
            "git_tag": "${{ github.ref }}", 
            "repo_url": "https://github.com/gini/bank-sdk-ios.git", 
            "repo_user": "${{ secrets.RELEASE_GITHUB_USER }}",
            "repo_password": "${{ secrets.RELEASE_GITHUB_PASSWORD }}",
            "ci": "true"
          }

    - name: Publish GiniBankSDKPinning package to the release repo
      uses: maierj/fastlane-action@v2.0.1
      with:
        lane: 'publish_swift_package'
        options: >
          { 
            "project_folder": "BankSDK",
            "package_folder": "GiniBankSDKPinning",
            "version_file_path": "BankSDK/GiniBankSDKPinning/Sources/GiniBankSDKPinning/GiniBankSDKPinningVersion.swift",
            "git_tag": "${{ github.ref }}", 
            "repo_url": "https://github.com/gini/bank-sdk-pinning-ios.git", 
            "repo_user": "${{ secrets.RELEASE_GITHUB_USER }}",
            "repo_password": "${{ secrets.RELEASE_GITHUB_PASSWORD }}",
            "ci": "true"
          }      
