name: Builds docs for Bank SDK

on:
  push:
    paths:
      - 'BankSDK/**'
  workflow_dispatch:
    tags-ignore:
      - '**'
  pull_request:
    paths:
      - 'BankSDK/**'
  
jobs:
  documentation:
    runs-on: macos-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1.5.1
      with:
        xcode-version: '14.3.1'

    - name: Checkout
      uses: actions/checkout@v4

    - name: setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.0'
        bundler-cache: true

    - name: Build GiniBankSDK documentation
      uses: maierj/fastlane-action@v3.1.0
      with:
        lane: 'build_docs'
        options: >
          { 
            "project_folder": "BankSDK",
            "package_folder": "GiniBankSDK"
          }

    - name: archive documentation
      uses: actions/upload-artifact@v3
      with:
        name: GiniBankSDKDocumentation
        path: BankSDK/GiniBankSDK/Documentation/Api        
