name: Builds docs for Capture SDK

on:
  workflow_dispatch:
    tags-ignore:
      - '**'
  pull_request:
    types: [opened, edited, reopened, synchronize]
    paths:
      - 'CaptureSDK/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'refs/tags/')}}
  
jobs:
  documentation:
    runs-on: macos-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: '15.3'

    - name: Checkout
      uses: actions/checkout@v4

    - name: setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.0'
        bundler-cache: true

    - name: Build GiniCaptureSDK documentation
      uses: maierj/fastlane-action@v3.1.0
      with:
        lane: 'build_docs'
        options: >
          { 
            "project_folder": "CaptureSDK",
            "package_folder": "GiniCaptureSDK"
          }

    - name: archive documentation
      uses: actions/upload-artifact@v4
      with:
        name: GiniCaptureSDKDocumentation
        path: CaptureSDK/GiniCaptureSDK/Documentation/Api        
