name: Release Health SDK
permissions:
  contents: write
on:
  push:
    tags:
      - 'GiniHealthSDK;[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
  
jobs:
  check:
    uses: gini/gini-mobile-ios/.github/workflows/health-sdk.check.yml@main
    secrets: inherit

  release:
    needs: check
    permissions:
      contents: write
    uses: ./.github/workflows/sdk.release.yml
    with:
      project_folder: 'HealthSDK'
      package_folder: 'GiniHealthSDK'
      version_file_path: 'HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/GiniHealthSDKVersion.swift'
      git_tag: ${{ github.ref }}
      repo_url: 'https://github.com/gini/health-sdk-ios.git'
    secrets:
      MOBILE_CI_APP_ID: ${{ secrets.MOBILE_CI_APP_ID }}
      MOBILE_CI_APP_PRIVATE_KEY: ${{ secrets.MOBILE_CI_APP_PRIVATE_KEY }}

  release-documentation:
    needs: release
    uses: gini/gini-mobile-ios/.github/workflows/health-sdk.publish.docs.yml@main
    secrets:
      MOBILE_CI_APP_ID: ${{ secrets.MOBILE_CI_APP_ID }}
      MOBILE_CI_APP_PRIVATE_KEY: ${{ secrets.MOBILE_CI_APP_PRIVATE_KEY }}
