name: Builds docs for Health API Library

on:
  push:
    paths:
      - 'HealthAPILibrary/**'
  workflow_dispatch:
    tags-ignore:
      - '**'
  pull_request:
    paths:
      - 'HealthAPILibrary/**'
  
jobs:
  documentation:
    runs-on: macos-latest    
    steps:
    - uses: maxim-lobanov/setup-xcode@v1.5.1
      with:
        xcode-version: '14.2'

    - name: Checkout
      uses: actions/checkout@v3

    - name: setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.0'
        bundler-cache: true

    - name: Build GiniHealthAPILibrary documentation
      uses: maierj/fastlane-action@v3.0.0
      with:
        lane: 'build_docs'
        options: >
          { 
            "project_folder": "HealthAPILibrary",
            "package_folder": "GiniHealthAPILibrary"
          }

    - name: archive documentation
      uses: actions/upload-artifact@v3
      with:
        name: GiniHealthAPILibraryDocumentation
        path: HealthAPILibrary/GiniHealthAPILibrary/Documentation/Api        
