name: Release Health API Library
permissions:
  contents: write
on:
  push:
    tags:
      - 'GiniHealthAPILibrary;[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  check:
    uses: gini/gini-mobile-ios/.github/workflows/health-api-library.check.yml@main
    secrets:
      GINI_MOBILE_TEST_CLIENT_SECRET: ${{ secrets.GINI_MOBILE_CI_PASSWORD }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  release:
    needs: check
    permissions:
      contents: write
    uses: ./.github/workflows/sdk.release.yml
    with:
      project_folder: 'HealthAPILibrary'
      package_folder: 'GiniHealthAPILibrary'
      version_file_path: 'HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/GiniHealthAPILibraryVersion.swift'
      git_tag: ${{ github.ref }}
      repo_url: 'https://github.com/gini/health-api-library-ios.git'
    secrets:
      MOBILE_CI_APP_ID: ${{ secrets.MOBILE_CI_APP_ID }}
      MOBILE_CI_APP_PRIVATE_KEY: ${{ secrets.MOBILE_CI_APP_PRIVATE_KEY }}


  release-documentation:
      needs: release
      uses: gini/gini-mobile-ios/.github/workflows/health-api-library.publish.docs.yml@main
      secrets:
        MOBILE_CI_APP_ID: ${{ secrets.MOBILE_CI_APP_ID }}
        MOBILE_CI_APP_PRIVATE_KEY: ${{ secrets.MOBILE_CI_APP_PRIVATE_KEY }}    
