name: Builds docs for Health API Library

on:
  push:
    paths:
      - 'HealthAPILibrary/**'
    tags-ignore:
      - '**'
  pull_request:
  
jobs:
  documentation:
    runs-on: macOS-11    
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.0'

    - name: Checkout
      uses: actions/checkout@v2

    - name: setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true

    - name: Build GiniHealthAPILibrary documentation
      uses: maierj/fastlane-action@v2.0.1
      with:
        lane: 'build_docs'
        options: >
          { 
            "project_folder": "HealthAPILibrary",
            "package_folder": "GiniHealthAPILibrary"
          }

    - name: archive documentation
      uses: actions/upload-artifact@v2
      with:
        name: GiniHealthAPILibraryDocumentation
        path: HealthAPILibrary/GiniHealthAPILibrary/Documentation/Api        
