name: infra-ci compliance secret scan
on:
  push:

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Check for trivyignore file
        id: check-trivyignore
        run: |
          if [[ -f .trivyignore.yaml ]]; then
            echo "trivyignore=.trivyignore.yaml" >> "$GITHUB_OUTPUT"
          fi

      - name: Run the Trivy scanner
        run: |
          docker run --rm \
            -v "$(pwd):/workspace" \
            -w /workspace \
            ${TRIVY_IGNOREFILE:+-e TRIVY_IGNOREFILE="${TRIVY_IGNOREFILE}"} \
            aquasec/trivy:0.69.2 \
            fs \
            --scanners secret \
            --format table \
            --exit-code 1 \
            .
        env:
          TRIVY_IGNOREFILE: ${{ steps.check-trivyignore.outputs.trivyignore }}
