name: Release Gini Internal Payment SDK
on:
  push:
    tags:
      - 'GiniInternalPaymentSDK;[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  check:
    uses: gini/gini-mobile-ios/.github/workflows/internal-payment-sdk.check.yml@main

  release:
    needs: check
    runs-on: macos-latest    
    steps:
    - uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: '15.3'

    - name: Checkout
      uses: actions/checkout@v4

    - name: setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.0'
        bundler-cache: true

    - name: Publish GiniInternalPaymentSDK package to the release repo
      uses: maierj/fastlane-action@v3.1.0
      with:
        lane: 'publish_swift_package'
        options: >
          { 
            "project_folder": "GiniComponents",
            "package_folder": "GiniInternalPaymentSDK",
            "version_file_path": "GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/GiniInternalPaymentSDKVersion.swift",
            "git_tag": "${{ github.ref }}", 
            "repo_url": "https://github.com/gini/internal-payment-sdk-ios.git",
            "repo_user": "${{ secrets.RELEASE_GITHUB_USER }}",
            "repo_password": "${{ secrets.RELEASE_GITHUB_PASSWORD }}",
            "ci": "true"
          }