name: Release Gini Internal Payment SDK
permissions:
  contents: write
  packages: write
on:
  push:
    tags:
      - 'GiniInternalPaymentSDK;[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  check:
    uses: gini/gini-mobile-ios/.github/workflows/internal-payment-sdk.check.yml@main

  release:
    needs: check
    runs-on: macos-latest   
    steps:
    - uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
      with:
        xcode-version: '15.3'

    - name: Checkout
      uses: actions/checkout@v4

    - name: setup ruby
      uses: ruby/setup-ruby@dffc446db9ba5a0c4446edb5bca1c5c473a806c5 # v1.245.0
      with:
        ruby-version: '3.2.0'
        bundler-cache: true

    - name: Publish GiniInternalPaymentSDK package to the release repo
      uses: maierj/fastlane-action@5a3b971aaa26776459bb26894d6c1a1a84a311a7 # v3.1.0
      with:
        lane: 'publish_swift_package'
        options: >
          { 
            "project_folder": "GiniComponents",
            "package_folder": "GiniInternalPaymentSDK",
            "version_file_path": "GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/GiniInternalPaymentSDKVersion.swift",
            "git_tag": "${{ github.ref }}", 
            "repo_url": "https://github.com/gini/internal-payment-sdk-ios.git",
            "repo_user": "${{ secrets.RELEASE_GITHUB_USER }}",
            "repo_password": "${{ secrets.RELEASE_GITHUB_PASSWORD }}",
            "ci": "true"
          }