name: Check Gini Internal Payment SDK
permissions:
  contents: read
on:
  pull_request:
   types: [opened, reopened, synchronize, ready_for_review]
   paths:
      - 'GiniComponents/GiniInternalPaymentSDK/**'
  workflow_call:
  workflow_dispatch:

jobs:
  check:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [GiniInternalPaymentSDK]
        destination: ['platform=iOS Simulator,OS=18.5,name=iPhone 16']
    steps:
    - uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
      with:
        xcode-version: '16.4'

    - name: Checkout
      uses: actions/checkout@v4

    - name: Check package GiniInternalPaymentSDK
      run: |
           cd GiniComponents/GiniInternalPaymentSDK
           swift package update

    - name: Build sdk targets
      run: |
        xcodebuild -workspace GiniMobile.xcworkspace -scheme "${{ matrix.target }}" -destination "${{ matrix.destination }}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO