name: Release Gini Internal Payment SDK
permissions:
  contents: write
on:
  push:
    tags:
      - 'GiniInternalPaymentSDK;[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  check:
    uses: ./.github/workflows/internal-payment-sdk.check.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  release:
    needs: check
    permissions:
      contents: write
    uses: ./.github/workflows/sdk.release.yml
    with:
      project_folder: 'GiniComponents/InternalPaymentSDK'
      package_folder: 'GiniInternalPaymentSDK'
      version_file_path: 'GiniComponents/InternalPaymentSDK/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/GiniInternalPaymentSDKVersion.swift'
      git_tag: ${{ github.ref }}
      repo_url: 'https://github.com/gini/internal-payment-sdk-ios.git'
    secrets:
      MOBILE_CI_APP_ID: ${{ secrets.MOBILE_CI_APP_ID }}
      MOBILE_CI_APP_PRIVATE_KEY: ${{ secrets.MOBILE_CI_APP_PRIVATE_KEY }}