name: Publish GiniMerchantSDKExample to Firebase Distribution
permissions:
  contents: read
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - 'MerchantSDK/**'
      - 'HealthAPILibrary/**'
      - 'GiniComponents/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-publish
  cancel-in-progress: ${{ !contains(github.ref, 'refs/tags/')}}

jobs:
  upload-version:
    environment: firebase-manual-deploy
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 3

      - uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
        with:
          xcode-version: '16.4'

      - name: Setup Ruby
        uses: ruby/setup-ruby@dffc446db9ba5a0c4446edb5bca1c5c473a806c5 # v1.245.0
        with:
          ruby-version: '3.2.0'
          bundler-cache: true

      - name: Setup provisioning profile
        uses: maierj/fastlane-action@5a3b971aaa26776459bb26894d6c1a1a84a311a7 # v3.1.0
        env:
          APP_IDENTIFIER: net.gini.merchantsdk.example
          DISTRIBUTION_TYPE: adhoc
          GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        with:
          lane: 'download_profiles'

      - name: Setup Manual Signing for Xcode project
        uses: maierj/fastlane-action@5a3b971aaa26776459bb26894d6c1a1a84a311a7 # v3.1.0
        with:
          lane: 'setup_manual_signing'
          options: >
            { 
              "project_path":"MerchantSDK/GiniMerchantSDKExample/GiniMerchantSDKExample.xcodeproj",
              "team_id":"JA825X8F7Z",
              "target":"GiniMerchantSDKExample",
              "bundle_identifier": "net.gini.merchantsdk.example",
              "profile_name": "match AdHoc net.gini.merchantsdk.example",
              "entitlements_file_path": "GiniMerchantSDKExample/GiniMerchantSDKExample.entitlements", 
              "ci": "true"
            }

      - name: Setup Credentials
        run: |
            sed -i '' \
            -e 's/clientID = "client_id"/clientID = "gini-mobile-test"/' \
            -e 's/clientPassword = "client_password"/clientPassword = "${{ secrets.GINI_MOBILE_TEST_CLIENT_SECRET }}"/' \
            MerchantSDK/GiniMerchantSDKExample/GiniMerchantSDKExample/Sources/CredentialsManager.swift
                
      - name: Archiving project
        run: |
            xcodebuild clean archive \
            -workspace GiniMobile.xcworkspace \
            -scheme "GiniMerchantSDKExample" \
            -archivePath ./GiniMerchantSDKExample.xcarchive \
            -configuration Release \
            -destination generic/platform=iOS \
            CODE_SIGN_IDENTITY="iPhone Distribution" \
            CODE_SIGNING_REQUIRED=NO \
            ONLY_ACTIVE_ARCH=NO \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM=JA825X8F7Z
    
      - name: Exporting .ipa
        run: |
            xcodebuild  \
            -exportArchive \
            -archivePath GiniMerchantSDKExample.xcarchive \
            -exportPath . \
            -exportOptionsPlist ExportOptionsMerchantExample.plist \
            -destination "generic/platform=iOS" \
            CODE_SIGNING_REQUIRED=YES \
            ONLY_ACTIVE_ARCH=NO \
            CODE_SIGN_STYLE=Manual

      - name: Check file existence
        uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6 # v3.0.0
        with:
          files: "*.ipa"
          fail: true

      - name: Install Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install -g firebase-tools@13.17.0
        shell: bash

      - name: Distribute Merchant sdk example apk to Firebase App Distribution
        id: distribute
        run: |
          chmod +x .github/publish_to_firebase.sh
          .github/publish_to_firebase.sh
        shell: bash
        env:
          INPUT_APPID: ${{ secrets.GINI_MERCHANT_SDK_EXAMPLE_APP_FIREBASE_ID }}
          INPUT_SERVICECREDENTIALSFILECONTENT: ${{ secrets.FIREBASE_CREDENTIAL_FILE_CONTENT }}
          INPUT_FILE: GiniMerchantSDKExample.ipa
          INPUT_GROUPS: testers
          INPUT_RELEASENOTES: |
            ${{ format('{{ {0} {1} }}', github.ref, github.sha) }}
            ${{ github.event.head_commit.message }}

      - name: Extract Jira ticket
        id: extract_jira_ticket
        run: |
          echo "Checking the last 3 commits for JIRA tickets..."
          jira_ticket_pattern='[A-Z]+-[0-9]+'
          jira_ticket=""

          commit_message=$(git log -1 --pretty=%B)
          jira_ticket=$(echo "$commit_message" | grep -oE "$jira_ticket_pattern" | head -1)

          if [[ -n "$jira_ticket" ]]; then
            echo "JIRA Ticket Found in Last Commit: $jira_ticket"
          else
            commit_message=$(git log --no-merges -1 --pretty=%B)
            jira_ticket=$(echo "$commit_message" | grep -oE "$jira_ticket_pattern" | head -1)

            if [[ -n "$jira_ticket" ]]; then
              echo "JIRA Ticket Found in Second Last Commit: $jira_ticket"
            else    
              commit_message=$(git log --no-merges -2 --pretty=%B)
              jira_ticket=$(echo "$commit_message" | grep -oE "$jira_ticket_pattern" | head -1)

              if [[ -n "$jira_ticket" ]]; then
                echo "JIRA Ticket Found in Third Last Commit: $jira_ticket"
              fi
            fi
          fi

          if [[ -n "$jira_ticket" ]]; then
            echo "JIRA_TICKET_NAME=${jira_ticket}" >> $GITHUB_ENV
          else
            echo "No JIRA Ticket found in the last 3 commits. Build link will not be posted to Jira. Pick it manually. This job will pass anyway."
            exit 0
          fi

      - name: Login to jira
        if: ${{ env.JIRA_TICKET_NAME != null }}
        uses: justin-jhg/gajira-login@3242a47d56cb5dd4373ed75b829d99ecdf5140df # v1.5.0
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_KEY }}

      - name: Comment on issue
        if: ${{ env.JIRA_TICKET_NAME != null }}
        uses: atlassian/gajira-comment@76589d6b6d0b94b1ca6b01171c01a6affb5d6701 # v3.0.0
        with:
          issue: ${{ env.JIRA_TICKET_NAME }}
          comment: Build merchant example app ${{ steps.distribute.outputs.FIREBASE_CONSOLE_URI }} and app tester build can be downloaded from here ${{ steps.distribute.outputs.TESTING_URI }}
      


          
